server {
    listen 80;

    root /usr/share/nginx/html;

    include /etc/nginx/mime.types;

    brotli on;
    brotli_static on;

    gzip on;
    gzip_static on;

    location / {
        try_files $uri $uri/ =404;
    }

    # JS Brotli
    location ~* \.js\.br$ {

        types {}
        default_type application/javascript;

        add_header Content-Encoding br always;

        expires 30d;
        add_header Cache-Control "public, immutable" always;

        try_files $uri =404;
    }

    # WASM Brotli
    location ~* \.wasm\.br$ {

        types {}
        default_type application/wasm;

        add_header Content-Encoding br always;

        expires 30d;
        add_header Cache-Control "public, immutable" always;

        try_files $uri =404;
    }

    # DATA Brotli
    location ~* \.(data|symbols\.json)\.br$ {

        types {}
        default_type application/octet-stream;

        add_header Content-Encoding br always;

        expires 30d;
        add_header Cache-Control "public, immutable" always;

        try_files $uri =404;
    }

    # wasm normal
    location ~* \.wasm$ {
        default_type application/wasm;
    }
}